version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: zabbix_mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - zabbix_mysql_data:/var/lib/mysql
    networks:
      - infra-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix_server
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - infra-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix_web
    depends_on:
      - zabbix-server
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Paris"
    ports:
      - "8080:80"
    networks:
      - infra-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix_agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: "zabbix-server"
    networks:
      - infra-net

volumes:
  zabbix_mysql_data:
  zabbix_server_data:

networks:
  infra-net:
    external: true
